import { Manrope } from 'next/font/google';
import "../globals.css";
import Navbar from '@/components/global/Navbar';
import Footer from '@/components/global/Footer';
import ScrollableLinks from "@/components/global/ScrollableLinks";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const manrope = Manrope({
  // weight: ['200', '300', '400', '500', '600', '700', '800'], // Specify the weights to load
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={manrope.className}>
      <body>
        <Navbar />
        <ScrollableLinks />
        {children}
        <Footer />
      </body>
    </html>
  );
}
