import { Manrope } from 'next/font/google';

import "../globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const manrope = Manrope({
  subsets: ['latin'],
  display: 'swap',
});

export default function OrderConfirmationLayout({ children }) {
  return (
    <html lang="en" className={manrope.className}>
      <body>
        {children}
      </body>
    </html>
  );
}
