import { Manrope } from 'next/font/google';
import "../globals.css";
import ProviderPolicyHeader from '@/components/enduser-panel/provider-policies/header';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const manrope = Manrope({
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={manrope.className}>
      <body>
        <ProviderPolicyHeader />
        {children}
      </body>

    </html>
  )
}
