import { Manrope } from 'next/font/google';
import "../globals.css";
import PricingHeader from '@/components/global/PricingHeader';
import ProgressSteps from '@/components/global/ProgressSteps';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const manrope = Manrope({
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={manrope.className}>
      <body>
        <PricingHeader />
        <ProgressSteps />
        {children}
      </body>
    </html>
  );
}
